#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'runningTime' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY arr as parameter.
#
def insertionSort1(start, arr):
    probe = arr[start]
    changed = 0
    
    for ind in range(start-1, -1, -1):
        if arr[ind] > probe:
            changed += 1
            arr[ind+1] = arr[ind]
        else:
            arr[ind+1] = probe
            break
    if arr[0] > probe:
        arr[0] = probe
        
    return changed

def insertionSort2(n, arr):
    res = 0
    for ind in range(1, len(arr)):
        res += insertionSort1(ind, arr)
        #print(" ".join(map(str, arr)))
    return res
def runningTime(arr):
    # Write your code here
    return insertionSort2(len(arr), arr)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = runningTime(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
